# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 21:02
from __future__ import unicode_literals
import json

from django.db import migrations
import v1.atomic_elements.organisms
import v1.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from wagtail.wagtailcore.blocks import StreamValue


def migrate_answer_to_streamfield(apps, schema_editor):  
    AnswerPage = apps.get_model('ask_cfpb', 'AnswerPage')   
    for page in AnswerPage.objects.all():
        text_block = {
            'type': 'text',
            'value': {
                'content': page.answer
            }
        }
        page.answer_content = StreamValue(page.answer_content.stream_block,[text_block],True,)
        page.save()
        for revision in page.revisions.all():    
            content = json.loads(revision.content_json) 
            content['answer_content'] = json.dumps([
                {
                    'type': 'text',
                    'value': {
                        'content': content['answer']
                    }
                }
            ])
            revision.content_json = json.dumps(content) 
            revision.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0020_rm_formfieldwithbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='answer_content',
            field=wagtail.wagtailcore.fields.StreamField([('text', wagtail.wagtailcore.blocks.StructBlock([('content', wagtail.wagtailcore.blocks.RichTextBlock(features=['link', 'ol', 'ul', 'h2', 'h3', 'document-link', 'image', 'embed'], label='Text'))])), ('table_block', v1.atomic_elements.organisms.AtomicTableBlock(table_options={'renderer': 'html'})), ('tip', wagtail.wagtailcore.blocks.StructBlock([(b'content', wagtail.wagtailcore.blocks.RichTextBlock(features=[b'link', b'document-link'], label=b'Tip'))])), ('warning', wagtail.wagtailcore.blocks.StructBlock([(b'content', wagtail.wagtailcore.blocks.RichTextBlock(features=[b'link', b'ol', b'ul', b'document-link', b'image', b'embed'], label=b'Warning'))])), ('heading', wagtail.wagtailcore.blocks.StructBlock([(b'text', v1.blocks.HeadingTextBlock(label=b'Heading text', required=False)), (b'level', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'heading1', b'Section heading'), (b'heading2', b'Sub section heading')]))]))], blank=True, verbose_name='Answer'),
        ),
        migrations.RunPython(migrate_answer_to_streamfield),
        migrations.RemoveField(
            model_name='answerpage',
            name='answer',
        ),
    ]
