# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 15:17
from __future__ import unicode_literals
import json

from django.db import migrations, models
from wagtail.wagtailcore.blocks import StreamValue
from bs4 import BeautifulSoup

def migrate_snippet_to_short_answer(apps, schema_editor):  
    AnswerPage = apps.get_model('ask_cfpb', 'AnswerPage')   
    for page in AnswerPage.objects.all():
        soup = BeautifulSoup(page.snippet)
        page.short_answer = soup.get_text()
        page.save()
        for revision in page.revisions.all():    
            content = json.loads(revision.content_json) 
            soup = BeautifulSoup(content['snippet'])
            content['short_answer'] = soup.get_text()
            revision.content_json = json.dumps(content) 
            revision.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0021_migrate_answer_to_streamfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='short_answer',
            field=models.TextField(blank=True, help_text='Optional answer intro.'),
        ),
        migrations.RunPython(migrate_snippet_to_short_answer),
    ]
