# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0026_seeallpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeallpage',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
